# Generated by Django 4.2.15 on 2024-08-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_unit_remove_ingredient_unit_type_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantitiy',
            field=models.IntegerField(default=0),
        ),
    ]
