# Generated by Django 4.2.15 on 2024-08-19 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_unit_quantity_ingredient_quantitiy'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantitiy',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='IngredientName',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.AddField(
            model_name='ingredientitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(to='menu.ingredientitem'),
        ),
    ]
