# Generated by Django 4.2.15 on 2024-08-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_category_priority_alter_dailymenu_served_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='priority',
            new_name='order',
        ),
    ]
