# Generated by Django 4.2.15 on 2024-08-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_category_is_active_dailymenu_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
