# Generated by Django 4.2.15 on 2024-08-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menuitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='servings',
            field=models.IntegerField(default=0),
        ),
    ]
