# Generated by Django 4.2.15 on 2024-09-02 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_dailymenu_served_at_alter_dailymenu_servings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='menu_items',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='ingredientitem',
            name='ingredient',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='menu.category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, to='menu.ingredientitem'),
        ),
    ]
