# Generated by Django 4.2.16 on 2024-09-05 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_dailymenu_menu_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
